version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    command: bash -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py add_currency_data && python manage.py runserver 0.0.0.0:8000"
    container_name: currency_converter
    env_file:
      - .env
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data: